//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShibaStoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBError
    {
        public int ErrorID { get; set; }
        public string ErrorText { get; set; }
    }
}
